from typing import Protocol

from xboxctl.models import Console, MediaAction, PowerAction, ProviderAction


class XboxProvider(Protocol):
    def list_consoles(self) -> tuple[Console, ...]: ...

    def status(self) -> Console: ...

    def launch(self, target: str) -> ProviderAction: ...

    def press(self, button: str, repeat: int) -> ProviderAction: ...

    def send_text(self, text: str) -> ProviderAction: ...

    def media(self, action: MediaAction) -> ProviderAction: ...

    def power(self, action: PowerAction) -> ProviderAction: ...
